[theme]
name = "dracula"

[icons]
name = "awesome6"

[[block]]
block = "custom"
command = "uname -r"
interval = "once"

[[block]]
block = "cpu"
format = "{utilization}"
interval = 3

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
clickable = true
interval = 3

[[block]]
block = "nvidia_gpu"
label = ""
show_memory = true
show_clocks = false
show_power_draw = true
interval = 3

[[block]]
block = "temperature"
collapsed = false
format = "{average}"
interval = 3

[[block]]
block = "sound"

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 3
